In [1]:
import torchvision

In [2]:
torchvision.__version__

'0.4.1'

In [15]:
fns

['jl_attempt.ipynb',
 'test.mp4',
 '.ipynb_checkpoints',
 'py_attempt.ipynb',
 '.gitattributes',
 'train.mp4',
 'train.txt']

In [28]:
import pandas as pd
df = pd.read_csv('train.txt', sep='\n', header=None)
df.columns = ['mph']
df.values

array([[28.105569],
       [28.105569],
       [28.106527],
       ...,
       [ 2.292917],
       [ 2.2606  ],
       [ 2.206759]])

             mph
0      28.105569
1      28.105569
2      28.106527
3      28.130404
4      28.109243
...          ...
20395   2.329180
20396   2.289795
20397   2.292917
20398   2.260600
20399   2.206759

[20400 rows x 1 columns]